spring.application.name=TourVista
spring.datasource.url=jdbc:postgresql://localhost:5433/TourVista
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
places.base-url=https://api.geoapify.com
places.api-key=${GEOAPIFY_API_KEY}
qwen.base-url=http://localhost:11434
qwen.model=qwen3:4b
